// <auto-generated />
using CodeF_Core_Demo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeF_Core_Demo.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20221122101741_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeF_Core_Demo.Context.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "New York",
                            CompanyName = "Dunder Mifflin",
                            Designation = "Manager",
                            Name = "Micheal",
                            Salary = 50000f
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "Scranton ",
                            CompanyName = "Dunder Mifflin",
                            Designation = "Developer",
                            Name = "Jim",
                            Salary = 30000f
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "New York",
                            CompanyName = "XYZ",
                            Designation = "Reginal Manager",
                            Name = "Dwight",
                            Salary = 30000f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
