// <auto-generated />
namespace L_M_S.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dbcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dbcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202211171257529_Db creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
